feat: add Hygraph support
ascorbic/unpic pull request #142
Opened 2024-11-08 22:28 UTC by mattwigham

2024-11-09 12:34 UTC, ascorbic commented
Thanks! Looking at the playground it doesn't seem to be cropping the images as expected. e.g. making this 100x600 gives a 100x100 image. Is there a param that can give the expected aspect ratio? The default should be equivalent to object-fit: cover, if it's supported.

2024-11-10 11:12 UTC, ascorbic commented
Thanks. Can you enable edits from maintainers on the PR please

2024-11-10 17:30 UTC, mattwigham commented
Hmm, apparently I don't have that option because the fork is on an organization. https://github.com/orgs/community/discussions/5634

2024-11-10 19:38 UTC, ascorbic commented
That's annoying. Can you update the branch then please. There should be a button just below this

2024-11-11 00:31 UTC, mattwigham commented
Done!

2024-11-11 07:11 UTC, ascorbic approved these changes
Thanks!

2024-11-11 07:27 UTC, ascorbic requested changes

2024-11-11 07:27 UTC, ascorbic commented on src/transformers/hygraph.ts
> +  props.transformations.resize.fit ||= "crop";
This needs to only be set if both width and height are provided. I think your previous version had a check for this. Currently this generates invalid URLs if only one dimension is provided. e.g. [this one](https://us-west-2.graphassets.com/cm2apl1zp07l506n66dmd9xo8/resize=fit:crop,width:100/auto_image/cm2tr64fx7gvu07n85chjmuno). You can catch errors like this by running `deno test --allow-net e2e.test.ts`

2024-11-11 15:15 UTC, ascorbic approved these changes

2024-11-11 15:15 UTC, merged